# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1192, 817)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setHandleWidth(10)
        self.splitter_2.setObjectName("splitter_2")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.splitter_2)
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 2, 1, 1)
        self.tBML = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.tBML.setObjectName("tBML")
        self.gridLayout_2.addWidget(self.tBML, 1, 3, 1, 1)
        self.sT = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.sT.setObjectName("sT")
        self.gridLayout_2.addWidget(self.sT, 5, 2, 1, 1)
        self.sNM = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.sNM.setObjectName("sNM")
        self.gridLayout_2.addWidget(self.sNM, 2, 2, 1, 1)
        self.tEM = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.tEM.setObjectName("tEM")
        self.gridLayout_2.addWidget(self.tEM, 6, 3, 1, 1)
        self.lM = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.lM.setObjectName("lM")
        self.gridLayout_2.addWidget(self.lM, 4, 0, 1, 1)
        self.fBML = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        self.fBML.setObjectName("fBML")
        self.fBML.addItem("")
        self.fBML.addItem("")
        self.fBML.addItem("")
        self.fBML.addItem("")
        self.gridLayout_2.addWidget(self.fBML, 1, 1, 1, 1)
        self.sEM = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.sEM.setObjectName("sEM")
        self.gridLayout_2.addWidget(self.sEM, 6, 2, 1, 1)
        self.fCMM = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        self.fCMM.setObjectName("fCMM")
        self.fCMM.addItem("")
        self.fCMM.addItem("")
        self.fCMM.addItem("")
        self.fCMM.addItem("")
        self.gridLayout_2.addWidget(self.fCMM, 7, 1, 1, 1)
        self.lT = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.lT.setObjectName("lT")
        self.gridLayout_2.addWidget(self.lT, 5, 0, 1, 1)
        self.fEM = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        self.fEM.setObjectName("fEM")
        self.fEM.addItem("")
        self.fEM.addItem("")
        self.fEM.addItem("")
        self.fEM.addItem("")
        self.gridLayout_2.addWidget(self.fEM, 6, 1, 1, 1)
        self.sM = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.sM.setObjectName("sM")
        self.gridLayout_2.addWidget(self.sM, 4, 2, 1, 1)
        self.lEM = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.lEM.setObjectName("lEM")
        self.gridLayout_2.addWidget(self.lEM, 6, 0, 1, 1)
        self.sBML = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.sBML.setObjectName("sBML")
        self.gridLayout_2.addWidget(self.sBML, 1, 2, 1, 1)
        self.tCMM = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.tCMM.setObjectName("tCMM")
        self.gridLayout_2.addWidget(self.tCMM, 7, 3, 1, 1)
        self.lBML = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.lBML.setObjectName("lBML")
        self.gridLayout_2.addWidget(self.lBML, 1, 0, 1, 1)
        self.sR = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.sR.setObjectName("sR")
        self.gridLayout_2.addWidget(self.sR, 3, 2, 1, 1)
        self.lR = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.lR.setObjectName("lR")
        self.gridLayout_2.addWidget(self.lR, 3, 0, 1, 1)
        self.tNM = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.tNM.setObjectName("tNM")
        self.gridLayout_2.addWidget(self.tNM, 2, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.lCMM_2 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.lCMM_2.setObjectName("lCMM_2")
        self.gridLayout_2.addWidget(self.lCMM_2, 7, 0, 1, 1)
        self.lNM = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.lNM.setObjectName("lNM")
        self.gridLayout_2.addWidget(self.lNM, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 1, 1, 1)
        self.tRMT = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.tRMT.setObjectName("tRMT")
        self.gridLayout_2.addWidget(self.tRMT, 3, 3, 1, 1)
        self.fNM = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        self.fNM.setObjectName("fNM")
        self.fNM.addItem("")
        self.fNM.addItem("")
        self.fNM.addItem("")
        self.fNM.addItem("")
        self.gridLayout_2.addWidget(self.fNM, 2, 1, 1, 1)
        self.fRMT = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        self.fRMT.setObjectName("fRMT")
        self.fRMT.addItem("")
        self.fRMT.addItem("")
        self.fRMT.addItem("")
        self.fRMT.addItem("")
        self.gridLayout_2.addWidget(self.fRMT, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 3, 1, 1)
        self.sCMM = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.sCMM.setObjectName("sCMM")
        self.gridLayout_2.addWidget(self.sCMM, 7, 2, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_2)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lCMM_8 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.lCMM_8.setObjectName("lCMM_8")
        self.gridLayout_4.addWidget(self.lCMM_8, 0, 0, 1, 1)
        self.lCMM_3 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.lCMM_3.setObjectName("lCMM_3")
        self.gridLayout_4.addWidget(self.lCMM_3, 1, 0, 1, 1)
        self.input = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.input.setObjectName("input")
        self.gridLayout_4.addWidget(self.input, 0, 1, 1, 1)
        self.output = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.output.setObjectName("output")
        self.gridLayout_4.addWidget(self.output, 1, 1, 1, 1)
        self.inputFind = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.inputFind.setObjectName("inputFind")
        self.gridLayout_4.addWidget(self.inputFind, 0, 2, 1, 1)
        self.outputFind = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.outputFind.setObjectName("outputFind")
        self.gridLayout_4.addWidget(self.outputFind, 1, 2, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_4)
        self.invertNM = QtWidgets.QCheckBox(self.verticalLayoutWidget_5)
        self.invertNM.setObjectName("invertNM")
        self.verticalLayout_9.addWidget(self.invertNM)
        self.debug = QtWidgets.QCheckBox(self.verticalLayoutWidget_5)
        self.debug.setObjectName("debug")
        self.verticalLayout_9.addWidget(self.debug)
        self.convert = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.convert.setObjectName("convert")
        self.verticalLayout_9.addWidget(self.convert)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget_5)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_9.addWidget(self.line_2)
        self.verticalLayout_8.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.find = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.find.setObjectName("find")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.find)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.replace = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.replace.setObjectName("replace")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.replace)
        self.verticalLayout_10.addLayout(self.formLayout_2)
        self.rename = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.rename.setObjectName("rename")
        self.verticalLayout_10.addWidget(self.rename)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget_5)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_10.addWidget(self.line)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lCMM_5 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.lCMM_5.setObjectName("lCMM_5")
        self.horizontalLayout_9.addWidget(self.lCMM_5)
        self.unpackPath = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.unpackPath.setObjectName("unpackPath")
        self.horizontalLayout_9.addWidget(self.unpackPath)
        self.unpackFind = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.unpackFind.setObjectName("unpackFind")
        self.horizontalLayout_9.addWidget(self.unpackFind)
        self.verticalLayout_10.addLayout(self.horizontalLayout_9)
        self.unpack = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.unpack.setObjectName("unpack")
        self.verticalLayout_10.addWidget(self.unpack)
        self.verticalLayout_8.addLayout(self.verticalLayout_10)
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.mPaths = QtWidgets.QListWidget(self.verticalLayoutWidget_2)
        self.mPaths.setObjectName("mPaths")
        self.horizontalLayout_12.addWidget(self.mPaths)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.mUp = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.mUp.setObjectName("mUp")
        self.verticalLayout_14.addWidget(self.mUp)
        self.mAdd = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.mAdd.setObjectName("mAdd")
        self.verticalLayout_14.addWidget(self.mAdd)
        self.mRemove = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.mRemove.setObjectName("mRemove")
        self.verticalLayout_14.addWidget(self.mRemove)
        self.mDown = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.mDown.setObjectName("mDown")
        self.verticalLayout_14.addWidget(self.mDown)
        self.horizontalLayout_12.addLayout(self.verticalLayout_14)
        self.verticalLayout_13.addLayout(self.horizontalLayout_12)
        self.merge = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.merge.setObjectName("merge")
        self.verticalLayout_13.addWidget(self.merge)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_13.addWidget(self.line_3)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pPaths = QtWidgets.QListWidget(self.verticalLayoutWidget_4)
        self.pPaths.setObjectName("pPaths")
        self.horizontalLayout_13.addWidget(self.pPaths)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.pUp = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pUp.setObjectName("pUp")
        self.verticalLayout_17.addWidget(self.pUp)
        self.pAdd = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pAdd.setObjectName("pAdd")
        self.verticalLayout_17.addWidget(self.pAdd)
        self.pRemove = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pRemove.setObjectName("pRemove")
        self.verticalLayout_17.addWidget(self.pRemove)
        self.pDown = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pDown.setObjectName("pDown")
        self.verticalLayout_17.addWidget(self.pDown)
        self.horizontalLayout_13.addLayout(self.verticalLayout_17)
        self.verticalLayout_16.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lCMM = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.lCMM.setObjectName("lCMM")
        self.horizontalLayout_14.addWidget(self.lCMM)
        self.packPath = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.packPath.setObjectName("packPath")
        self.horizontalLayout_14.addWidget(self.packPath)
        self.packFind = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.packFind.setObjectName("packFind")
        self.horizontalLayout_14.addWidget(self.packFind)
        self.verticalLayout_16.addLayout(self.horizontalLayout_14)
        self.pack = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pack.setObjectName("pack")
        self.verticalLayout_16.addWidget(self.pack)
        self.verticalLayout_15.addWidget(self.splitter_2)
        self.console = QtWidgets.QTextEdit(self.centralwidget)
        self.console.setObjectName("console")
        self.verticalLayout_15.addWidget(self.console)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1192, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.fBML.setCurrentIndex(2)
        self.fCMM.setCurrentIndex(2)
        self.fEM.setCurrentIndex(2)
        self.fNM.setCurrentIndex(0)
        self.fRMT.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "Extension"))
        self.tBML.setText(_translate("MainWindow", "BML"))
        self.sT.setText(_translate("MainWindow", "Transparency"))
        self.sNM.setText(_translate("MainWindow", "Normal"))
        self.tEM.setText(_translate("MainWindow", "EM"))
        self.lM.setText(_translate("MainWindow", "Metalicness"))
        self.fBML.setCurrentText(_translate("MainWindow", "BC7_UNORM"))
        self.fBML.setItemText(0, _translate("MainWindow", "BC5_UNORM"))
        self.fBML.setItemText(1, _translate("MainWindow", "BC1_UNORM_SRGB"))
        self.fBML.setItemText(2, _translate("MainWindow", "BC7_UNORM"))
        self.fBML.setItemText(3, _translate("MainWindow", "BC7_UNORM_SRGB"))
        self.sEM.setText(_translate("MainWindow", "Emissive"))
        self.fCMM.setCurrentText(_translate("MainWindow", "BC7_UNORM"))
        self.fCMM.setItemText(0, _translate("MainWindow", "BC5_UNORM"))
        self.fCMM.setItemText(1, _translate("MainWindow", "BC1_UNORM_SRGB"))
        self.fCMM.setItemText(2, _translate("MainWindow", "BC7_UNORM"))
        self.fCMM.setItemText(3, _translate("MainWindow", "BC7_UNORM_SRGB"))
        self.lT.setText(_translate("MainWindow", "Transparency"))
        self.fEM.setCurrentText(_translate("MainWindow", "BC7_UNORM"))
        self.fEM.setItemText(0, _translate("MainWindow", "BC5_UNORM"))
        self.fEM.setItemText(1, _translate("MainWindow", "BC1_UNORM_SRGB"))
        self.fEM.setItemText(2, _translate("MainWindow", "BC7_UNORM"))
        self.fEM.setItemText(3, _translate("MainWindow", "BC7_UNORM_SRGB"))
        self.sM.setText(_translate("MainWindow", "Metallic"))
        self.lEM.setText(_translate("MainWindow", "Emissive"))
        self.sBML.setText(_translate("MainWindow", "BaseColor"))
        self.tCMM.setText(_translate("MainWindow", "CMM"))
        self.lBML.setText(_translate("MainWindow", "Diffuse"))
        self.sR.setText(_translate("MainWindow", "Roughness"))
        self.lR.setText(_translate("MainWindow", "Roughness"))
        self.tNM.setText(_translate("MainWindow", "NM"))
        self.label_8.setText(_translate("MainWindow", "Label"))
        self.lCMM_2.setText(_translate("MainWindow", "Custom Coloring"))
        self.lNM.setText(_translate("MainWindow", "Normal"))
        self.label_9.setText(_translate("MainWindow", "Format"))
        self.tRMT.setText(_translate("MainWindow", "RMT"))
        self.fNM.setItemText(0, _translate("MainWindow", "BC5_UNORM"))
        self.fNM.setItemText(1, _translate("MainWindow", "BC1_UNORM_SRGB"))
        self.fNM.setItemText(2, _translate("MainWindow", "BC7_UNORM"))
        self.fNM.setItemText(3, _translate("MainWindow", "BC7_UNORM_SRGB"))
        self.fRMT.setCurrentText(_translate("MainWindow", "BC7_UNORM"))
        self.fRMT.setItemText(0, _translate("MainWindow", "BC5_UNORM"))
        self.fRMT.setItemText(1, _translate("MainWindow", "BC1_UNORM_SRGB"))
        self.fRMT.setItemText(2, _translate("MainWindow", "BC7_UNORM"))
        self.fRMT.setItemText(3, _translate("MainWindow", "BC7_UNORM_SRGB"))
        self.label_10.setText(_translate("MainWindow", "Target Extension"))
        self.sCMM.setText(_translate("MainWindow", "Custom"))
        self.lCMM_8.setText(_translate("MainWindow", "Input Folder"))
        self.lCMM_3.setText(_translate("MainWindow", "Output Folder"))
        self.inputFind.setText(_translate("MainWindow", "..."))
        self.outputFind.setText(_translate("MainWindow", "..."))
        self.invertNM.setText(_translate("MainWindow", "Invert NM"))
        self.debug.setText(_translate("MainWindow", "Debug Mode"))
        self.convert.setText(_translate("MainWindow", "Convert"))
        self.label_11.setText(_translate("MainWindow", "Find"))
        self.label_12.setText(_translate("MainWindow", "Replace"))
        self.rename.setText(_translate("MainWindow", "Rename"))
        self.lCMM_5.setText(_translate("MainWindow", "Input Tex"))
        self.unpackFind.setText(_translate("MainWindow", "..."))
        self.unpack.setText(_translate("MainWindow", "Unpack"))
        self.mUp.setText(_translate("MainWindow", "^"))
        self.mAdd.setText(_translate("MainWindow", "Add"))
        self.mRemove.setText(_translate("MainWindow", "Delete"))
        self.mDown.setText(_translate("MainWindow", "v"))
        self.merge.setText(_translate("MainWindow", "Merge Texture Sets"))
        self.pUp.setText(_translate("MainWindow", "^"))
        self.pAdd.setText(_translate("MainWindow", "Add"))
        self.pRemove.setText(_translate("MainWindow", "Delete"))
        self.pDown.setText(_translate("MainWindow", "v"))
        self.lCMM.setText(_translate("MainWindow", "Output Tex"))
        self.packFind.setText(_translate("MainWindow", "..."))
        self.pack.setText(_translate("MainWindow", "Pack"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

